---
- name: add sysctl parameters into /etc/sysctl.conf
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    block: |
      vm.overcommit_memory=1
      net.core.somaxconn = 511

- name: add sysctl parameters into /etc/security/limits.conf
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nofile 655350
      * hard nofile 655350
      * hard memlock unlimited
      * soft memlock unlimited

- name: make the parameters work
  ansible.builtin.shell:
      cmd: sysctl -p

- name: add into profile with bin path
  ansible.builtin.blockinfile:
    path: /etc/profile
    block: |
      export PATH=$PATH:/usr/local/redis/
