---
# according to /etc/ansible/hosts Prod Group. match the server name with inventory IP
- name: set server hostname
  become: true
  become_method: sudo
  become_user: root
  hosts: uat
  vars:
    hostnames:
      10.17.4.112: wfx-uat-xxljob
      10.17.4.49: wfx-uat-syncoteam_frontend
      10.17.4.140: wfx-uat-syncoteam_backend01
      10.17.4.235: wfx-uat-syncoteam_backend02
      10.17.4.229: wfx-uat-syncolab_frontend
      10.17.4.76: wfx-uat-syncolab_backend
      10.17.4.74: wfx-uat-lowcode_frontend
      10.17.4.172: wfx-uat-nacos
      10.17.4.57: wfx-uat-nginx_portal
      10.17.4.150: wfx-uat-syncowork_frontend
      10.17.4.252: wfx-uat-redis01
      10.17.4.38: wfx-uat-syncowork_dify
      10.17.4.70: wfx-uat-redis02
      10.17.4.79: wfx-uat-redis03
      10.17.4.139: wfx-uat-mysql01
      10.17.4.52: wfx-uat-syncolab_sonarqube
      10.17.4.86: wfx-uat-lowcode_backend01
      10.17.4.224: wfx-uat-bigscreen_postgre
      10.17.4.42: wfx-uat-lowcode_backend02
      10.17.4.247: wfx-uat-kettle
      10.17.4.131: wfx-uat-syncohour_frontend
      10.17.4.236: wfx-uat-syncowork_base
      10.17.4.68: wfx-uat-syncohour_backend01
      10.17.4.206: wfx-uat-syncohour_backend02
 
  tasks:
  - name: fetch IP address
    set_fact:
      host_ip: "{{ hostvars[inventory_hostname].inventory_hostname }}"

  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ hostnames[host_ip] }}"

