---
- name: Configure Broker
  template:
    src: broker.conf.j2
    dest: "/home/rocketmq/rocketmq-all-5.1.3-bin-release/conf/broker.conf"

- name: Copy systemd service file
  ansible.builtin.copy:
    src: broker.service
    dest: /etc/systemd/system/broker.service

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable Broker service
  systemd:
    name: broker
    state: started
    enabled: yes
