---
- name: Configure NameServer
  template:
    src: namesrv.conf.j2
    dest: "/home/rocketmq/rocketmq-all-5.1.3-bin-release/conf/controller.conf"

- name: Copy systemd service file
  ansible.builtin.copy:
    src: nameserver.service
    dest: /etc/systemd/system/nameserver.service

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable NameServer service
  systemd:
    name: nameserver
    state: started
    enabled: yes
